name = "spotify-proxy"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.production]
name = "spotify-proxy"

[env.development]
name = "spotify-proxy-dev"

# KV namespace for storing tokens and user data
[[kv_namespaces]]
binding = "SPOTIFY_DATA"
id = "8e96b5c8fd92469c9988d89773b4a5d9"
preview_id = "d99f068858a5401cbf4463132959349e"

# Environment variables (set these via wrangler secret put)
[vars]
ENVIRONMENT = "development"

# For deployment, you'll need to set these secrets via Cloudflare Dashboard:
# API_KEY - Your secure API key for authentication
# SPOTIFY_CLIENT_ID - Your Spotify app's Client ID
# SPOTIFY_CLIENT_SECRET - Your Spotify app's Client Secret

# All secrets can be set via the Cloudflare Dashboard:
# Workers & Pages → Your Worker → Settings → Variables → Add variable (with Encrypt checked)
